/** @deprecated Nutze `welt.ts`. Bleibt als Name für alte Imports. */
export {
  type KartePatch,
  type WeltAuflage,
  auflageFuerSicht,
  anzahlAuflagen,
  hatAuflage,
  karteSchluessel,
  ladeKarten,
  ladeWelt,
  loescheAuflage,
  loescheKarte,
  merkeAuflage,
  patchFuerSicht,
  rueckgaengigAuflage,
  setzeSpielleiterAktiv,
  setzeWeltAktiv,
  sichtSchluessel,
  speichereKarte,
  spielleiterAktiv,
  weltAktiv,
  wendePatchAn,
} from "./welt";
